import type { Metadata } from 'next'
import './styles/globals.css'
import AppHeader from '../_components/AppHeader/app_header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className='container mx-auto'>
        <AppHeader />
        {children}
      </body>
    </html>
  )
}